# You have been contracted by the National Park Service to create a program 
# that can track revenue for its parks. Specifically, they would like you to 
# implement the following features:

# Create a Park class. Each park has a unique name and admission price, as well as a way to read that data.
# Each park has vehicles that entered the park, as well as a way to read that data.
# Each park can list all passengers that were in the vehicles that entered the park.
# Each park can calculate revenue generated. Revenue is generated by charging the admission price per adult that entered the park.
# Build upon your existing code from the first two iterations to implement this functionality.

# Method Name	Return Value (type)
# name	String
# admission_price	integer
# vehicles	Array of Vehicle objects
# add_vehicle(vehicle)	vehicles (Array of Vehicle objects)
# passengers	Array of Passenger objects
# revenue	Integer

require './lib/vehicle'
require './lib/passenger'
require './lib/park'

RSpec.describe Park do 

  before(:each) do

    @the_banks = Park.new({name: "The Banks", admission_price: 14})

    @vehicle = Vehicle.new("2001", "Honda", "Civic")    
    @charlie = Passenger.new({"name" => "Charlie", "age" => 18})    
    @jude = Passenger.new({"name" => "Jude", "age" => 20})    
    @taylor = Passenger.new({"name" => "Taylor", "age" => 12})    

  end 

  describe "initialize" do

    it "exists" do 
      expect(@the_banks).to be_a(Park)
    end

    it "has readable attributes" do

      expect(@the_banks.name).to eq("The Banks")
      expect(@the_banks.admission_price).to eq(14)
      expect(@the_banks.vehicles).to eq([])
      
    end

  end



end
